services:
  - type: web
    name: seatserve
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /health/
    autoDeployOnPush: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: django-insecure-render-production-key-min-32-chars
      - key: ALLOWED_HOSTS
        value: seatserve.onrender.com,.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: SECURE_HSTS_PRELOAD
        value: "True"
      - key: CORS_ALLOWED_ORIGINS
        value: https://seatserve.onrender.com
      - key: PORT
        value: "8000"
